# Clipboard history — persist text and image clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursor theme
exec-once = hyprctl setcursor $cursorTheme $cursorSize
